# $File: //ASP/tec/gui/qevcl/trunk/qeVCLApp/Makefile $
# $Revision: #1 $
# $DateTime: 2020/06/08 15:51:50 $
# Last checked in by: $Author: starritt $
#

TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Db*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *ui*))
include $(TOP)/configure/RULES_DIRS

# end
