# File: qeVCLTestApp/Db/Makefile
# DateTime: Mon May 26 17:17:29 2025
# Last checked in by: starritt
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB += dbl_slit_test.template
DB += dbl_slit_test.substitutions
DB += filter_screen.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


# end
