# $File: //ASP/tec/gui/qevcl/trunk/qeVCLTestApp/Db/Makefile $
# $Revision: #2 $
# $DateTime: 2021/03/23 17:16:58 $
# Last checked in by: $Author: starritt $
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB += dbl_slit_test.template
DB += dbl_slit_test.substitutions
DB += filter_screen.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


# end
