# $File: //ASP/tec/gui/qevcl/trunk/configure/Makefile $
# $Revision: #1 $
# $DateTime: 2020/06/08 15:51:50 $
# Last checked in by: $Author: starritt $
#

TOP=..

include $(TOP)/configure/CONFIG

TARGETS = $(CONFIG_TARGETS)
CONFIGS += $(subst ../,,$(wildcard $(CONFIG_INSTALLS)))

include $(TOP)/configure/RULES

# end
